name: biblianime
services:
  ### API ###
  api:
    build:
      context: .
    ports:
      - 8080:8080
    # `depends_on` indique à Docker Compose de démarrer la base de données avant votre application.
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/biblianimedb
  ### POSTGRESQL ###
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=biblianimedb
      - POSTGRES_USER=biblianimeuser
      #- POSTGRES_PASSWORD=password
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "biblianimeuser" ]
      interval: 10s
      timeout: 5s
      retries: 5
  ### PGADMIN ###
  pgadmin:
    image: dpage/pgadmin4:8.7
    restart: always
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=plopez@email.fr
      - PGADMIN_DEFAULT_PASSWORD=dpagepass
      #- PGADMIN_DEFAULT_PASSWORD_FILE=file
    expose:
      - 80:80
      - 443:443

# Le volume `db-data` persiste les données de la base entre les redémarrages du conteneur.
volumes:
  db-data:

# Le secret `db-password` est utilisé pour définir le mot de passe de la base de données.
# Vous devez créer le fichier `db/password.txt` et y ajouter un mot de passe de votre choix avant d'utiliser la base de données.
# un mot de passe de votre choix avant de lancer `docker-compose up`.
secrets:
  db-password:
    file: db/password.txt
