name: biblianime
services:

  ### API ###
  api:
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - network
    # `depends_on` indique à Docker Compose de démarrer la base de données avant votre application.
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  ### POSTGRESQL ###
  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    secrets:
      - db-password
    networks:
      - network
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  ### PGADMIN ###
  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    secrets:
      - pgadmin-password
    networks:
      - network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8082:80
      - 8083:443
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
volumes:
  db-data:
  pgadmin-data:
networks:
  network:
secrets:
  db-password:
    file: db/db-password.txt
  pgadmin-password:
    file: pgadmin/pgadmin-password.txt